services:
  cpp-dev-tools:
    build:
      args:
        BUILD_PYTORCH: "false"
        ENABLE_AI: "false"
        ENABLE_LLM: "false"
        ENABLE_QUANTUM: "false"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    init: true

    volumes:
      - vscode-extensions:/root/.vscode-server/extensions
      - vscode-insiders:/root/.vscode-server-insiders/extensions

volumes:
  vscode-extensions:
  vscode-insiders: